version: '3.5'
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: johndoe
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
