name: Build and deploy

on:
  push:
    branches: [ deployment ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag waitsafe-queue-service:latest

      - name: Stop old container
        run: docker kill waitsafe-queue-service
        continue-on-error: true

      - name: Run latest
        run: docker run -d --rm -p 8080:3000 --name waitsafe-queue-service waitsafe-queue-service:latest
